### ISSUE TITLE
Fatal Error during activation

### ISSUE THREAD

**Issue by mcgreenwood** [amirandalibi/perception#3]
Thanks for sharing your code!

Since I activated the Plugin, I receive an HTTP-error while uploading. 
![screenshot 2017-12-20 11 06 32](https://user-images.githubusercontent.com/6052412/34201789-f4c6dcb4-e575-11e7-9c6a-efb704138908.png)
My API console didn´t log any incoming requests, so I think it gets stuck before.
If I deactivate the plugin I can upload the files again.

Do you have an Idea why that happens?

Another Question: Where do you store the Tags? In the Description?

**Comment by amirandalibi** [comment]
Hi there!
It's really hard to say without seeing the error logs, Did you also check your PHP console log?
One of the common issues is that Vision API is not enabled for the Project. You can check the status in here:
`https://console.developers.google.com/apis/api/vision.googleapis.com/overview?project=YOUR-PROJECT-NAME`
I'll improve the error messaging in the next version.
Also, all the tags are being stored in `wp_postmeta` table under `_wp_attached_google_vision`
