### ISSUE TITLE
How to display image metadata?

### ISSUE THREAD

**Issue by dennis-jauernig** [amirandalibi/perception#5]
Hey!

Thanks for the plugin btw! 

So there is no value in the description/title whatever metadata field for a given image, but its in the database under wp_postmeta.

How do i 'echo' the value for a specific id? Is it necessary to use a mysql command or is there a build in wordpress function for it?

thanks!

**Comment by amirandalibi** [comment]
All the tags are stored in `wp_attached_google_vision` as a comma-separated string.
This section is designated for issues related to the code, and such question could be answered in [stackoverflow](stackoverflow.com) or other similar forums. But all you need could be found here https://developer.wordpress.org/reference/functions/get_post_meta/
